name: Feature Request
description: Suggest a new idea for ThunderAI
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for suggesting new ideas only!

        If you need to report a bug, please use the [bug][bg] form.

        [bg]: https://github.com/micz/ThunderAI/issues/new?template=bug_report.yml
  - type: textarea
    validations:
      required: true
    id: idea
    attributes:
      label: Your idea
      description: >-
        Describe the idea you'd like to see implemented in ThunderAI.

        Provide a clear and concise description.
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    id: value
    attributes:
      label: Value
      description: >-
        What value does this idea bring to ThunderAI? How does it improve the
        user experience or functionality?
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: >
        If you have any additional information, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
